/* LEAP language switcher — English is the source language; Polish is applied client-side. */
(() => {
  const polish = new Map(Object.entries({
    'About': 'O projekcie',
    'Studies': 'Badania',
    'Team': 'Zespół',
    'Protocols': 'Protokoły',
    'Publications': 'Publikacje',
    'Prior Research': 'Dotychczasowe badania',
    'Rationale': 'Uzasadnienie',
    'Contact': 'Kontakt',
    'Researcher Portal': 'Portal badacza',
    'Medical University of Gdańsk': 'Gdański Uniwersytet Medyczny',
    'Redefining how we': 'Nowe spojrzenie na',
    'understand and treat': 'rozumienie i leczenie',
    'apophyseal pain': 'zmian przeciążeniowych apofiz',
    'in youth athletes': 'u młodych sportowców',
    'A multidomain research program combining biomarkers, ultrasound imaging, functional testing, and clinical trials to advance evidence-based care for Osgood–Schlatter disease and Sever disease.': 'Wielowymiarowy program badawczy łączący biomarkery, badania ultrasonograficzne, testy funkcjonalne i badania kliniczne, aby rozwijać opiekę opartą na dowodach naukowych w zmianach Osgood–Schlatter i zmianach Severa.',
    'View Studies': 'Zobacz badania',
    '● Recruiting · NCT07446517': '● Rekrutacja · NCT07446517',
    '● Recruiting · NCT07521280': '● Rekrutacja · NCT07521280',
    'Scroll': 'Przewiń',
    'The Problem': 'Problem',
    'Why LEAP matters': 'Dlaczego LEAP jest ważny',
    'Lower-extremity apophyseal pathologies — Osgood–Schlatter disease and Sever disease — are among the most prevalent musculoskeletal conditions in youth athletes, yet they remain poorly understood and undertreated.': 'Zmiany apofiz kończyn dolnych — w tym zmiany Osgood–Schlatter i zmiany Severa — należą do najczęstszych problemów układu mięśniowo-szkieletowego u młodych sportowców, a mimo to pozostają słabo poznane i niedostatecznie leczone.',
    'Current clinical practice frequently defaults to a "wait and see" approach, despite growing evidence that these conditions are not trivially self-limiting. Recent data show that adults with a history of Osgood–Schlatter disease have significantly worse knee health and a higher risk of developing patellar tendinopathy (Krommes et al., 2025). Meanwhile, 25% of practitioners still recommend watchful waiting as the primary strategy (Lyng et al., 2020).': 'W praktyce klinicznej często dominuje podejście „poczekamy, zobaczymy”, mimo rosnących dowodów, że te zmiany nie są banalnie samoograniczające. Najnowsze dane wskazują, że dorośli ze zmianami Osgood–Schlatter w wywiadzie mają istotnie gorszy stan zdrowia kolan i większe ryzyko tendinopatii więzadła rzepki (Krommes i wsp., 2025). Tymczasem 25% praktyków nadal zaleca wyczekującą obserwację jako podstawową strategię (Lyng i wsp., 2020).',
    'No high-quality randomized controlled trial of conservative treatment currently exists for this population. The LEAP project aims to close that gap.': 'W tej populacji nie przeprowadzono dotąd wysokiej jakości randomizowanego badania kontrolowanego leczenia zachowawczego. Projekt LEAP ma wypełnić tę lukę.',
    'Read the full scientific rationale →': 'Przeczytaj pełne uzasadnienie naukowe →',
    'of practitioners still use "wait and see" as primary management': 'praktyków nadal stosuje „poczekamy, zobaczymy” jako podstawowe postępowanie',
    'high-quality RCTs of conservative treatment exist in this population': 'wysokiej jakości badań RCT leczenia zachowawczego istnieje w tej populacji',
    'risk of patellar tendinopathy in adults with prior Osgood–Schlatter': 'ryzyko tendinopatii więzadła rzepki u dorosłych ze zmianami Osgood–Schlatter w wywiadzie',
    'years — typical onset range; peak at 9–12 depending on condition and sex': 'lat — typowy wiek wystąpienia; szczyt 9–12 lat, zależnie od lokalizacji zmian i płci',
    'Our Approach': 'Nasze podejście',
    'A multidomain framework': 'Wielowymiarowe ramy badawcze',
    'Biomarker Panel': 'Panel biomarkerów',
    'Cartilage turnover, bone turnover, and inflammatory markers (CRP, vitamin D, IL-family) to characterize the biological landscape of apophyseal pathology.': 'Markery obrotu chrząstki i kości oraz stanu zapalnego (CRP, witamina D, rodzina IL), które pozwalają opisać biologiczne podłoże zmian przeciążeniowych apofiz.',
    'Ultrasound Imaging': 'Obrazowanie ultrasonograficzne',
    'Structural assessment of the apophysis at baseline and post-intervention to track morphological changes alongside clinical outcomes.': 'Ocena strukturalna apofizy na początku badania i po interwencji, umożliwiająca śledzenie zmian morfologicznych wraz z wynikami klinicznymi.',
    'Functional Testing': 'Testy funkcjonalne',
    'Validated performance-based and patient-reported outcomes (KOOS-Child, OxAFQ-C, NPRS) alongside biomechanical assessment.': 'Walidowane wyniki oparte na wykonaniu zadań i zgłaszane przez pacjentów (KOOS-Child, OxAFQ-C, NPRS) wraz z oceną biomechaniczną.',
    'Controlled Trials': 'Badania kontrolowane',
    'Rigorous randomized and prospective designs — from a double-blind sham-controlled LLLT pilot RCT to an individualized rehabilitation feasibility study.': 'Rygorystyczne projekty randomizowane i prospektywne — od pilotażowego RCT LLLT z podwójnym zaślepieniem i pozorowaną interwencją po badanie wykonalności zindywidualizowanej rehabilitacji.',
    'Registered Studies': 'Zarejestrowane badania',
    'Clinical trials & OSF preregistrations': 'Badania kliniczne i prerejestracje OSF',
    'LEAP-PHEN and LEAP-REHAB are methodologically linked clinical trials registered on ClinicalTrials.gov. Three additional studies are preregistered on OSF — covering conceptual, mixed-methods, and reliability work underpinning the programme.': 'LEAP-PHEN i LEAP-REHAB to powiązane metodologicznie badania kliniczne zarejestrowane w ClinicalTrials.gov. Trzy dodatkowe badania zostały prerejestrowane w OSF i obejmują prace koncepcyjne, mieszane metody oraz wiarygodność pomiarów, na których opiera się program.',
    'CONCEPTUAL FRAMEWORK': 'RAMY KONCEPCYJNE',
    'MIXED-METHODS PROMs': 'PROMs — METODY MIESZANE',
    'PAIN PROVOKING TEST': 'TEST PROWOKUJĄCY BÓL',
    'Multidomain Phenotyping of Lower-Extremity Apophyseal Pain in Youth Athletes Using Biomarkers, Ultrasound, and Functional Testing, with an Embedded Double-Blind Pilot Photobiomodulation Trial': 'Wielowymiarowe fenotypowanie zmian przeciążeniowych apofiz kończyn dolnych u młodych sportowców z wykorzystaniem biomarkerów, ultrasonografii i testów funkcjonalnych oraz wbudowanym, podwójnie zaślepionym pilotażowym badaniem fotobiomodulacji.',
    '● Recruiting': '● Rekrutacja',
    'Work Package 1 — Cross-Sectional Phenotyping': 'Pakiet roboczy 1 — fenotypowanie przekrojowe',
    'Comparison of biomarker profiles, ultrasound findings, and functional parameters between youth athletes with LEAP (OSD + Sever) and a healthy matched control group. Each participant provides 5 ml of venous blood for analysis of CBC, CRP, vitamin D, and bone and cartilage turnover markers.': 'Porównanie profili biomarkerów, wyników ultrasonografii i parametrów funkcjonalnych między młodymi sportowcami z LEAP (OSD + Sever) a dobraną zdrową grupą kontrolną. Każdy uczestnik oddaje 5 ml krwi żylnej do analizy morfologii, CRP, witaminy D oraz markerów obrotu kostnego i chrzęstnego.',
    'Work Package 2 — Pilot RCT (LLLT vs. Sham)': 'Pakiet roboczy 2 — pilotażowe RCT (LLLT vs. pozorowana interwencja)',
    'The first randomized, double-blind, sham-controlled trial of low-level laser therapy (photobiomodulation) in youth athletes with apophyseal pain. Active LLLT uses a class 3B GaAlAs laser applied to the symptomatic apophyseal region over 10 sessions / 2 weeks.': 'Pierwsze randomizowane, podwójnie zaślepione badanie z pozorowaną interwencją dotyczące laseroterapii niskoenergetycznej (fotobiomodulacji) u młodych sportowców ze zmianami przeciążeniowymi apofiz. Aktywna LLLT wykorzystuje laser GaAlAs klasy 3B, stosowany w objawowej okolicy apofizy w 10 sesjach przez 2 tygodnie.',
    'Masking:': 'Zaślepienie:', 'Triple — participant, investigator, outcomes assessor': 'potrójne — uczestnik, badacz, oceniający wyniki',
    'Allocation:': 'Przydział:', '1:1 randomization (active LLLT vs. sham)': 'randomizacja 1:1 (aktywne LLLT vs. pozorowana interwencja)',
    'Primary objective:': 'Cel główny:', 'Feasibility (recruitment, retention, adherence, safety)': 'wykonalność (rekrutacja, utrzymanie w badaniu, przestrzeganie zaleceń, bezpieczeństwo)',
    'Secondary:': 'Drugorzędowe:', 'Between-group differences in pain (NPRS) and function': 'różnice między grupami w bólu (NPRS) i funkcji',
    'Exploratory:': 'Eksploracyjne:', 'Biomarker and ultrasound changes to design a future full-scale RCT': 'zmiany biomarkerów i obrazu USG do zaprojektowania przyszłego pełnoskalowego RCT',
    'Scientific Rationale for LLLT': 'Naukowe uzasadnienie LLLT',
    'A 2022 meta-analysis demonstrated significant reductions in pain and dysfunction with LLLT in tendinopathy and plantar fasciitis (Naterstad et al.). LLLT reduces pro-inflammatory cytokines (IL-1, IL-6, IL-8, IL-18) and mediators (PGE2, TNF-α, IL-6), with mechanism overlap relevant to apophyseal pathology (Berni et al., 2023). No prior evidence exists for LLLT in LEAP.': 'Metaanaliza z 2022 r. wykazała istotne zmniejszenie bólu i dysfunkcji po LLLT w tendinopatiach i zapaleniu rozcięgna podeszwowego (Naterstad i wsp.). LLLT obniża stężenie prozapalnych cytokin (IL-1, IL-6, IL-8, IL-18) i mediatorów (PGE2, TNF-α, IL-6), których mechanizmy są istotne dla patologii apofiz (Berni i wsp., 2023). Brakuje wcześniejszych dowodów dla LLLT w LEAP.',
    'Status': 'Status', 'Recruiting': 'Rekrutacja', 'Study type': 'Typ badania', 'Interventional': 'Interwencyjne', 'Design': 'Projekt', 'Parallel RCT, triple-masked': 'RCT równoległe, potrójnie zaślepione', 'Age': 'Wiek', 'Started': 'Rozpoczęcie', 'Primary completion': 'Zakończenie główne', 'Full completion': 'Pełne zakończenie', 'Ethics': 'Zgoda etyczna', 'Study Timeline': 'Harmonogram badania', 'Baseline — WP1 cross-section + WP2 randomization': 'Wartość wyjściowa — WP1 przekrojowo + randomizacja WP2', 'Intervention': 'Interwencja', '10 sessions over 2 weeks (LLLT vs. sham)': '10 sesji w ciągu 2 tygodni (LLLT vs. pozorowana interwencja)', 'Post-intervention assessment': 'Ocena po interwencji', '3-month follow-up': 'Kontrola po 3 miesiącach', 'View on ClinicalTrials.gov ↗': 'Zobacz w ClinicalTrials.gov ↗',
    'Feasibility, Clinical Response, and Exploratory Predictors of an Individualized Load-Based Rehabilitation Pathway in Youth Athletes With Osgood-Schlatter Disease or Sever Disease: A Prospective Single-Arm Interventional Study': 'Wykonalność, odpowiedź kliniczna i eksploracyjne predyktory zindywidualizowanej ścieżki rehabilitacji opartej na obciążeniu u młodych sportowców ze zmianami Osgood–Schlatter lub zmianami Severa: prospektywne jednoramienne badanie interwencyjne.',
    'Rehabilitation Pathway': 'Ścieżka rehabilitacji',
    'A 12-week individualized rehabilitation program built on a standardized core framework, individualized by symptom response rather than fixed timelines. The program targets load tolerance and movement quality in tasks relevant to youth sport.': '12-tygodniowy, zindywidualizowany program rehabilitacji oparty na ustandaryzowanym rdzeniu, dostosowywany do odpowiedzi objawów, a nie sztywnego harmonogramu. Program rozwija tolerancję obciążenia i jakość ruchu w zadaniach istotnych w sporcie młodzieżowym.',
    'Education and pain monitoring (activity diary)': 'Edukacja i monitorowanie bólu (dziennik aktywności)', 'Activity-ladder approach with symptom-guided progression': 'Podejście drabiny aktywności z progresją kierowaną objawami', 'Motor-control training and basic strength exposure': 'Trening kontroli motorycznej i podstawowa ekspozycja siłowa', 'Squatting, single-leg control, step/split-squat, calf loading': 'Przysiady, kontrola jednonóż, wejścia/wykroki, obciążanie łydki', 'Gradual return to running, jumping, deceleration, sport-specific tasks': 'Stopniowy powrót do biegania, skoków, hamowania i zadań specyficznych dla sportu',
    'Entry Pathways': 'Ścieżki włączenia', 'Participants may enter through three routes (used for descriptive subgroup analyses, not treatment arms):': 'Uczestnicy mogą być włączani trzema drogami (wykorzystywanymi do opisowych analiz podgrup, a nie jako ramiona leczenia):', 'Post-trial:': 'Po badaniu:', 'after completing LEAP-PHEN (NCT07446517)': 'po ukończeniu LEAP-PHEN (NCT07446517)', 'Direct entry — active symptoms:': 'Włączenie bezpośrednie — aktywne objawy:', 'current OSD or Sever pain': 'obecny ból związany ze zmianami OSD lub zmianami Severa', 'Direct entry — residual:': 'Włączenie bezpośrednie — objawy resztkowe:', 'previous symptoms, low-irritability presentation': 'wcześniejsze objawy, obraz o małej drażliwości',
    'Primary Objectives (Feasibility)': 'Cele główne (wykonalność)', 'Attendance at planned in-person physiotherapy review visits': 'Frekwencja na zaplanowanych wizytach kontrolnych u fizjoterapeuty', 'Home-exercise adherence ≥70% of study weeks': 'Realizacja ćwiczeń domowych w ≥70% tygodni badania', 'Intervention fidelity (protocol elements delivered and documented)': 'Wierność interwencji (realizacja i dokumentacja elementów protokołu)', 'Retention at follow-up assessment': 'Utrzymanie uczestników do oceny kontrolnej', 'Safety — adverse events count and classification': 'Bezpieczeństwo — liczba i klasyfikacja zdarzeń niepożądanych',
    'Secondary Outcomes': 'Wyniki drugorzędowe', 'Open Data': 'Otwarte dane', 'De-identified individual participant data, statistical analysis plan, and analytic code will be made openly available through OSF after primary publication, for at least 5 years.': 'Pozbawione danych identyfikujących dane indywidualne uczestników, plan analizy statystycznej i kod analityczny zostaną udostępnione otwarcie przez OSF po publikacji głównej, na co najmniej 5 lat.',
    'Research Team': 'Zespół badawczy', 'Principal Investigator': 'Kierownik projektu', 'Project Supervisor': 'Opiekun naukowy', 'Ultrasonography': 'Ultrasonografia', 'Biochemical Research': 'Badania biochemiczne', 'Orthopaedic Surgery': 'Ortopedia', 'PhD Candidate': 'Doktorant', 'Senior Collaborators': 'Główni współpracownicy', 'Institutional Affiliations & Funders': 'Instytucje i źródła finansowania', 'Medical University of Gdańsk · Fahrenheit Universities': 'Gdański Uniwersytet Medyczny · Uczelnie Fahrenheita', 'National Science Centre (NCN)': 'Narodowe Centrum Nauki (NCN)', 'Research Assistant': 'Asystent badawczy',
    'Transparency & Open Science': 'Transparentność i otwarta nauka', 'Protocols, Preregistrations & Related Work': 'Protokoły, prerejestracje i powiązane prace', 'All study designs and protocols are publicly registered. Related preregistrations cover methodology, conceptual foundations, and measurement properties of tools used across the LEAP program.': 'Wszystkie projekty i protokoły badań są publicznie zarejestrowane. Powiązane prerejestracje obejmują metodologię, podstawy koncepcyjne oraz właściwości pomiarowe narzędzi stosowanych w programie LEAP.', 'Clinical Trial Registrations': 'Rejestracje badań klinicznych', 'Registered March 2026 · Status: Recruiting': 'Zarejestrowano w marcu 2026 · Status: rekrutacja', 'Registered May 2026 · Status: Recruiting': 'Zarejestrowano w maju 2026 · Status: rekrutacja', 'OSF Preregistrations': 'Prerejestracje OSF', 'Get in Touch': 'Skontaktuj się', 'Address': 'Adres', 'Ethics & Compliance': 'Etyka i zgodność', 'Both studies have received ethics approval from the Bioethics Committee for Scientific Research, Medical University of Gdańsk.': 'Oba badania uzyskały zgodę Komisji Bioetycznej ds. Badań Naukowych Gdańskiego Uniwersytetu Medycznego.', 'Approval:': 'Zgoda:', 'Committee:': 'Komisja:', 'Compliance:': 'Zgodność:', 'Lower Extremity Apophyseal Pain Research Program': 'Program badań nad zmianami przeciążeniowymi apofiz kończyn dolnych', 'Funded by GUMed IDUB (71-01428) & NCN MINIATURA 9 (DEC-2025/09/X/NZ7/01758)': 'Finansowane przez GUMed IDUB (71-01428) i NCN MINIATURA 9 (DEC-2025/09/X/NZ7/01758)',
    '← Back to LEAP Project': '← Wróć do projektu LEAP', 'Scientific Background': 'Podstawy naukowe', 'Study Rationale & Research Framework': 'Uzasadnienie badania i ramy badawcze', 'A structured account of the evidence gaps, conceptual framework, and scientific justification underlying the LEAP research program.': 'Usystematyzowane omówienie luk w dowodach, ram koncepcyjnych i naukowego uzasadnienia programu badawczego LEAP.', 'On this page': 'Na tej stronie', 'Research Gap': 'Luka badawcza', 'Study Rationale': 'Uzasadnienie badania', 'Conceptual Framework': 'Ramy koncepcyjne', 'Contents': 'Spis treści', 'Prevalence & burden': 'Częstość i obciążenie', 'Current practice': 'Obecna praktyka', 'Evidence vacuum': 'Brak dowodów', 'Long-term consequences': 'Konsekwencje długoterminowe', 'Multidomain design': 'Projekt wielowymiarowy', 'Biomarker rationale': 'Uzasadnienie biomarkerów', 'LLLT rationale': 'Uzasadnienie LLLT', 'Rehabilitation rationale': 'Uzasadnienie rehabilitacji', 'Mechanobiology': 'Mechanobiologia', 'Maturation window': 'Okno dojrzewania', 'Context & diagnosis': 'Kontekst i diagnostyka', 'Why a multidomain design?': 'Dlaczego projekt wielowymiarowy?', 'Mechanobiological load–capacity model': 'Mechanobiologiczny model obciążenie–zdolność tkanki', 'Time-limited vulnerability window': 'Ograniczone w czasie okno podatności', 'Context, diagnosis, and clinical interpretation': 'Kontekst, diagnostyka i interpretacja kliniczna', 'Key References': 'Kluczowe piśmiennictwo', 'References': 'Piśmiennictwo',
    'Lower-extremity apophyseal pathologies (LEAP) — principally Osgood–Schlatter disease (OSD), Sever disease (calcaneal apophysitis), and Sinding–Larsen–Johansson syndrome (SLJ) — are among the most prevalent musculoskeletal conditions in skeletally immature athletes. OSD affects an estimated 10–20% of adolescents engaged in sport, with higher rates in sports involving repetitive jumping, running, and kicking. Sever disease accounts for up to 8% of all sports-related injuries presenting to pediatric sports medicine clinics.': 'Zmiany apofiz kończyn dolnych (LEAP) — przede wszystkim zmiany Osgood–Schlatter (OSD), zmiany Severa (w obrębie apofizy kości piętowej) i zmiany Sindinga–Larsena–Johanssona (SLJ) — należą do najczęstszych problemów układu mięśniowo-szkieletowego u sportowców niedojrzałych szkieletowo. Zmiany Osgood–Schlatter dotyczą szacunkowo 10–20% aktywnych sportowo nastolatków, częściej w dyscyplinach z powtarzalnymi skokami, bieganiem i kopaniem. Zmiany Severa stanowią do 8% wszystkich urazów związanych ze sportem zgłaszanych do pediatrycznych poradni medycyny sportowej.',
    'Despite this prevalence, the biological, biomechanical, and contextual factors that determine who develops symptoms, who recovers, and who experiences persistent or recurrent pain remain poorly characterised. Clinical presentations vary substantially — from self-limiting episodes to prolonged, functionally disabling courses — yet no validated staging system, prognostic biomarker, or clinically actionable predictor of outcome currently exists.': 'Mimo tej częstości biologiczne, biomechaniczne i kontekstowe czynniki decydujące o tym, u kogo wystąpią objawy, kto wyzdrowieje, a kto doświadczy utrzymującego się lub nawrotowego bólu, pozostają słabo scharakteryzowane. Obraz kliniczny jest bardzo zróżnicowany — od epizodów samoograniczających po długotrwały przebieg ograniczający funkcję — jednak nie istnieje zwalidowany system stopniowania, biomarker prognostyczny ani użyteczny klinicznie predyktor wyniku.',
    'The "wait and see" problem': 'Problem podejścia „poczekamy, zobaczymy”',
    'Many young patients are told to rest and wait for growth plates to close. This approach is frustrating for athletes and families, offers no functional support, and may delay the development of adequate load-tolerance — leaving athletes vulnerable to re-injury on return to sport.': 'Wielu młodym pacjentom zaleca się odpoczynek i oczekiwanie na zamknięcie chrząstek wzrostowych. To podejście frustruje sportowców i ich rodziny, nie zapewnia wsparcia funkcjonalnego i może opóźniać rozwój odpowiedniej tolerancji obciążenia — pozostawiając sportowców podatnymi na ponowny uraz po powrocie do sportu.',
    'The evidence vacuum': 'Luka w dowodach',
    'A critical review of the literature reveals a striking absence of high-quality interventional evidence. No randomized controlled trial of any conservative treatment currently exists for LEAP in a youth athlete population. The available studies are characterised by small samples, non-randomized designs, heterogeneous case definitions, short follow-up periods, and a near-exclusive focus on symptomatic outcomes without any mechanistic or biomarker data.': 'Krytyczny przegląd piśmiennictwa ujawnia uderzający brak wysokiej jakości dowodów interwencyjnych. Nie istnieje obecnie żadne randomizowane badanie kontrolowane jakiegokolwiek leczenia zachowawczego LEAP w populacji młodych sportowców. Dostępne prace charakteryzują się małymi próbami, nierandomizowanymi projektami, niejednorodnymi definicjami przypadków, krótką obserwacją i niemal wyłącznym skupieniem na objawach, bez danych mechanistycznych lub biomarkerowych.',
    'This evidence vacuum has direct clinical consequences. Without comparative effectiveness data, clinicians cannot make evidence-based recommendations. Without mechanistic data, it is impossible to know whether treatments that reduce pain do so by addressing the underlying tissue pathology or merely by masking symptoms. Without validated outcome measures adapted to this population, measurement in both research and clinical practice remains inconsistent.': 'Ten brak dowodów ma bezpośrednie konsekwencje kliniczne. Bez danych o skuteczności porównawczej klinicyści nie mogą wydawać zaleceń opartych na dowodach. Bez danych mechanistycznych nie wiadomo, czy metody zmniejszające ból wpływają na podstawową patologię tkanki, czy jedynie maskują objawy. Bez zwalidowanych miar wyniku dostosowanych do tej populacji pomiary zarówno w badaniach, jak i praktyce klinicznej pozostają niespójne.',
    'Long-term consequences': 'Konsekwencje długoterminowe',
    'The assumption that LEAP is a benign, self-limiting condition has been directly challenged by recent longitudinal data. Krommes et al. (2025) demonstrated that adults with a history of OSD exhibit significantly worse knee health scores and a substantially higher risk of developing patellar tendinopathy compared to matched controls without OSD history. This finding reframes the clinical significance of the condition: inadequate management during the symptomatic phase may have lasting consequences for musculoskeletal health into adulthood.': 'Założenie, że zmiany LEAP mają łagodny i samoograniczający się przebieg, zostało bezpośrednio podważone przez najnowsze dane podłużne. Krommes i wsp. (2025) wykazali, że dorośli z przebytą OSD mają istotnie gorsze wskaźniki zdrowia kolana i znacząco wyższe ryzyko rozwoju tendinopatii więzadła rzepki niż dobrane osoby bez OSD w wywiadzie. Odkrycie to zmienia znaczenie kliniczne tych zmian: niewystarczające postępowanie w fazie objawowej może mieć trwałe konsekwencje dla zdrowia układu mięśniowo-szkieletowego w dorosłości.',
    'Why a multidomain design?': 'Dlaczego projekt wielowymiarowy?',
    'Single-domain studies — focusing solely on pain, or only on imaging, or only on a clinical intervention — cannot capture the multifactorial nature of LEAP. Pain is an imperfect proxy for tissue state. Imaging changes do not always correspond to symptom severity. Function and participation outcomes matter independently of biological measures.': 'Badania jednodziedzinowe — koncentrujące się wyłącznie na bólu, obrazowaniu lub interwencji klinicznej — nie mogą uchwycić wieloczynnikowej natury LEAP. Ból jest niedoskonałym wskaźnikiem stanu tkanki. Zmiany w obrazowaniu nie zawsze odpowiadają nasileniu objawów. Wyniki dotyczące funkcji i uczestnictwa są istotne niezależnie od miar biologicznych.',
    'The LEAP-PHEN design integrates three parallel data streams — biomarkers, ultrasound, and functional/patient-reported outcomes — measured at the same time points in the same participants. This allows cross-domain associations to be examined prospectively and provides a richer characterisation of the condition than any single-domain approach. It also generates the measurement infrastructure (validated tools, reference ranges, baseline data) needed to power and design a future full-scale RCT.': 'Projekt LEAP-PHEN łączy trzy równoległe strumienie danych — biomarkery, ultrasonografię i wyniki funkcjonalne zgłaszane przez pacjentów — mierzone w tych samych punktach czasowych u tych samych uczestników. Umożliwia to prospektywne badanie związków między domenami i daje pełniejszą charakterystykę tych zmian niż jakiekolwiek podejście jednodziedzinowe. Tworzy też infrastrukturę pomiarową (zwalidowane narzędzia, zakresy referencyjne, dane wyjściowe) potrzebną do oszacowania liczebności i zaprojektowania przyszłego pełnoskalowego RCT.',
    'Pilot logic': 'Logika badania pilotażowego',
    'Both LEAP-PHEN and LEAP-REHAB are explicitly designed as feasibility and pilot studies. Their primary outputs are not definitive treatment effects but rather the data and operational evidence needed to justify, power, and correctly design future confirmatory trials. This is methodologically appropriate given the complete absence of prior controlled data.': 'LEAP-PHEN i LEAP-REHAB zostały jednoznacznie zaprojektowane jako badania wykonalności i pilotażowe. Ich głównymi wynikami nie są rozstrzygające efekty leczenia, lecz dane i dowody operacyjne potrzebne do uzasadnienia, oszacowania liczebności oraz właściwego zaprojektowania przyszłych badań potwierdzających. Jest to metodologicznie właściwe wobec całkowitego braku wcześniejszych danych kontrolowanych.',
    'Biomarker rationale': 'Uzasadnienie biomarkerów',
    'Bone and cartilage biomarkers offer a window into tissue-level processes that are invisible to clinical examination and ultrasound. In the context of apophyseal pathology, relevant biological processes include:': 'Biomarkery kostne i chrzęstne dają wgląd w procesy zachodzące na poziomie tkanki, niewidoczne w badaniu klinicznym i ultrasonografii. W kontekście patologii apofiz istotne procesy biologiczne obejmują:',
    'Rationale for low-level laser therapy (LLLT)': 'Uzasadnienie laseroterapii niskoenergetycznej (LLLT)',
    'The mechanistic rationale for LLLT in LEAP is supported by several converging lines of evidence:': 'Mechanistyczne uzasadnienie LLLT w LEAP potwierdza kilka zbieżnych linii dowodów:',
    'Rationale for individualized load-based rehabilitation': 'Uzasadnienie zindywidualizowanej rehabilitacji opartej na obciążeniu',
    'Current rehabilitation approaches for LEAP are largely empirical, rest-focused, and symptom-suppressive. An activity-ladder, symptom-guided rehabilitation model — grounded in load management principles from tendinopathy rehabilitation literature — offers a conceptually coherent alternative that targets load tolerance and graduated return to sport rather than symptom avoidance.': 'Obecne podejścia rehabilitacyjne w LEAP są w dużej mierze empiryczne, skoncentrowane na odpoczynku i tłumieniu objawów. Model rehabilitacji oparty na drabinie aktywności i kierowany objawami — osadzony w zasadach zarządzania obciążeniem znanych z rehabilitacji tendinopatii — oferuje spójną koncepcyjnie alternatywę ukierunkowaną na tolerancję obciążenia i stopniowy powrót do sportu, zamiast unikania objawów.',
    'The core principles of the LEAP-REHAB pathway are:': 'Główne zasady ścieżki LEAP-REHAB to:',
    'The LEAP program is grounded in an apophyseal-specific conceptual framework developed through a registered scoping review (OSF:': 'Program LEAP opiera się na specyficznych dla apofiz ramach koncepcyjnych opracowanych w zarejestrowanym przeglądzie zakresowym (OSF:',
    'Mechanobiological load–capacity model': 'Mechanobiologiczny model obciążenie–zdolność tkanki',
    'Mechanical Demand': 'Wymaganie mechaniczne', 'Tissue Capacity': 'Zdolność tkanki', 'Apophyseal pathology': 'Zmiany przeciążeniowe apofiz',
    'Research output': 'Dorobek naukowy', 'My research sits at the intersection of developmental musculoskeletal biology and applied sports science. I study how the growing skeleton responds to athletic load — and what happens when that response goes wrong. Apophyseal pathologies in youth athletes are my primary focus: conditions that are common, consequential, and almost entirely without evidence-based treatment. In parallel, I investigate the broader landscape of youth athlete development — maturation, movement quality, specialization, and asymmetry — because understanding who is at risk, and why, is inseparable from knowing how to help them.': 'Moje badania leżą na styku biologii rozwojowej układu mięśniowo-szkieletowego i stosowanej nauki o sporcie. Badam, jak rosnący szkielet reaguje na obciążenie sportowe — i co dzieje się, gdy ta odpowiedź zawodzi. Zmiany przeciążeniowe apofiz u młodych sportowców są moim głównym obszarem zainteresowania: są częste, istotne klinicznie i niemal całkowicie pozbawione leczenia opartego na dowodach. Równolegle badam szersze zagadnienia rozwoju młodego sportowca — dojrzewanie, jakość ruchu, specjalizację i asymetrię — ponieważ zrozumienie, kto jest zagrożony i dlaczego, jest nierozerwalne z wiedzą, jak mu pomóc.', 'Selected publications': 'Wybrane publikacje', 'Publication record': 'Dorobek publikacyjny', 'Jump to': 'Przejdź do', 'Apophyseal injuries': 'Zmiany przeciążeniowe apofiz', 'Youth athlete research': 'Badania nad młodymi sportowcami', 'Line of research 01': 'Obszar badawczy 01', 'Apophyseal Injuries in Youth Athletes': 'Zmiany przeciążeniowe apofiz u młodych sportowców', 'Clinical characterisation, long-term consequences, and the case for evidence-based management of Osgood–Schlatter disease, Sever disease, and Sinding–Larsen–Johansson syndrome.': 'Charakterystyka kliniczna, konsekwencje długoterminowe i uzasadnienie postępowania opartego na dowodach w zmianach Osgood–Schlatter, zmianach Severa oraz zmianach Sindinga–Larsena–Johanssona.', 'Polish-language commentary': 'Komentarz w języku polskim', 'Key argument': 'Główny argument', 'Key finding': 'Kluczowe ustalenie', 'Open Access': 'Otwarty dostęp', 'Line of research 02': 'Obszar badawczy 02', 'Youth Athlete Development': 'Rozwój młodego sportowca', 'Maturation, movement quality, specialization, and injury risk in the developing athlete — the broader context in which apophyseal pathology occurs.': 'Dojrzewanie, jakość ruchu, specjalizacja i ryzyko urazu u rozwijającego się sportowca — szerszy kontekst występowania zmian przeciążeniowych apofiz.'
  }));

  const titlePl = {
    'index.html': 'Projekt LEAP — zmiany przeciążeniowe apofiz kończyn dolnych u młodych sportowców',
    'rationale.html': 'Uzasadnienie badania — Projekt LEAP',
    'publications.html': 'Publikacje — Projekt LEAP · Bartosz Wilczyński'
  };

  const normalize = value => value.replace(/\s+/g, ' ').trim();
  const originalNodes = new WeakMap();

  function translatePage() {
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        const parent = node.parentElement;
        return parent && !['SCRIPT', 'STYLE', 'SVG'].includes(parent.tagName) && normalize(node.nodeValue)
          ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => {
      if (!originalNodes.has(node)) originalNodes.set(node, node.nodeValue);
      const source = originalNodes.get(node);
      const translation = polish.get(normalize(source));
      if (translation) {
        const leading = source.match(/^\s*/)?.[0] || '';
        const trailing = source.match(/\s*$/)?.[0] || '';
        node.nodeValue = `${leading}${translation}${trailing}`;
      }
    });
  }

  function restoreEnglish() {
    document.querySelectorAll('*').forEach(element => {
      element.childNodes.forEach(node => {
        if (node.nodeType === Node.TEXT_NODE && originalNodes.has(node)) node.nodeValue = originalNodes.get(node);
      });
    });
  }

  function setLanguage(language) {
    const isPolish = language === 'pl';
    if (isPolish) translatePage(); else restoreEnglish();
    document.querySelectorAll('a[href="portal.html"]').forEach(link => {
      const navigationItem = link.closest('li');
      (navigationItem || link).hidden = !isPolish;
    });
    document.documentElement.lang = isPolish ? 'pl' : 'en';
    const page = location.pathname.split('/').pop() || 'index.html';
    document.title = isPolish ? (titlePl[page] || titlePl['index.html']) : document.querySelector('title').dataset.enTitle || document.title;
    document.querySelectorAll('.language-button').forEach(button => {
      const active = button.dataset.language === language;
      button.setAttribute('aria-pressed', String(active));
    });
    localStorage.setItem('leap-language', language);
  }

  const title = document.querySelector('title');
  if (title) title.dataset.enTitle = title.textContent;
  document.querySelectorAll('.language-button').forEach(button => button.addEventListener('click', () => setLanguage(button.dataset.language)));
  setLanguage(localStorage.getItem('leap-language') === 'pl' ? 'pl' : 'en');
})();
